//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.LabTest = new HashSet<LabTest>();
        }
    
        public int appointment_id { get; set; }
        public int animal_id { get; set; }
        public int veterenarian_id { get; set; }
        public Nullable<System.DateTime> appointment_date { get; set; }
        public string reason { get; set; }
        public string appointment_result { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Veterenarian Veterenarian { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabTest> LabTest { get; set; }
    }
}
