//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int MessageId { get; set; }
        public Nullable<int> SenderId { get; set; }
        public Nullable<int> ReceiverId { get; set; }
        public string Content { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string SenderRole { get; set; }
        public string ReceiverRole { get; set; }
    
        public virtual Veterenarian Veterenarian { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
