//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetImages
    {
        public int image_id { get; set; }
        public int animal_id { get; set; }
        public byte[] image { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual Animal Animal { get; set; }
    }
}
