//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTest
    {
        public int labtest_id { get; set; }
        public Nullable<int> appointment_id { get; set; }
        public Nullable<int> test_type_id { get; set; }
        public string result { get; set; }
        public Nullable<System.DateTime> conducted_at { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual TestTypes TestTypes { get; set; }
    }
}
